version: '3.3'
services:
    postgres:
     container_name: postgres
     build: ./postgres
     ports:
       - '5435:5432'
     volumes:
       - ./postgres/data:/var/lib/postgresql/data
     environment:
       POSTGRES_HOST_AUTH_METHOD: "trust"
       POSTGRES_DB: "diasoft_test"
       POSTGRES_USER: "test"
       POSTGRES_PASSWORD: "pass"
     networks:
       frontend:
         ipv4_address: 192.168.212.6
    tomcat:
     container_name: tomcat
     build: ./tomcat
     ports:
       - '8888:8080'
     depends_on:
       - postgres  
     networks:
       frontend:
        ipv4_address: 192.168.212.5     
networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.212.0/24



